version: '2'
services:
  app:
    build: .
    command: sh -c "python manage.py makemigrations data && python manage.py migrate data && python telegram.py"
    restart: always
    environment:
      BOT_TOKEN:
    depends_on:
      - db
  db:
    image: postgres:9-alpine
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: 'tgvkbot'
      POSTGRES_PASSWORD: 'postgres'

volumes:
  db:
    driver: local